# Generated by Django 3.1.5 on 2021-08-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praxismethoden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='category',
        ),
        migrations.AddField(
            model_name='method',
            name='category',
            field=models.ManyToManyField(related_name='categories_method', to='praxismethoden.Category'),
        ),
    ]
