# Generated by Django 3.1.5 on 2021-08-02 18:57

from django.conf import settings
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('praxismethoden', '0002_auto_20210801_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='category',
            field=models.ManyToManyField(null=True, related_name='categories_method', to='praxismethoden.Category'),
        ),
        migrations.AlterField(
            model_name='method',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='methods_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
