# Generated by Django 3.1.5 on 2021-08-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praxismethoden', '0003_auto_20210824_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='file',
        ),
    ]
