# Generated by Django 3.1.5 on 2021-08-03 12:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('praxismethoden', '0003_auto_20210802_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='body',
        ),
        migrations.AddField(
            model_name='method',
            name='desc',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
