# Generated by Django 3.1.5 on 2021-08-03 15:28

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('praxismethoden', '0004_auto_20210803_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categories_method', to='praxismethoden.Category'),
        ),
        migrations.AlterField(
            model_name='method',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='methods_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
