# Generated by Django 3.1.5 on 2021-08-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praxismethoden', '0005_method_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='file_raw',
        ),
    ]
