# Generated by Django 3.1.5 on 2021-08-09 12:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praxismethoden', '0006_auto_20210804_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='author',
        ),
        migrations.AlterField(
            model_name='method',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Der Text hier ist detailierter als der Kurztext. Zum Beispiel hält dieser zusätzliche Informationen oder Beispiele.', null=True, verbose_name='Text detail'),
        ),
        migrations.AlterField(
            model_name='method',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Der hier eingegebene Kurztext, wird in der Kachelansicht angezeigt und dient zur Information und dazu, den Besucher neugierig zu machen.', null=True, verbose_name='Text kurz'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', ckeditor.fields.RichTextField(blank=True, help_text='Das Semesterprogramm.', null=True, verbose_name='Semesterprogram')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
