# Generated by Django 3.1.5 on 2021-08-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praxismethoden', '0007_auto_20210809_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgaben',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2048)),
                ('prio', models.PositiveSmallIntegerField(choices=[(1, 'Hoch'), (2, 'Mittel'), (3, 'Tief')], default=2)),
            ],
        ),
    ]
