# Generated by Django 3.1.5 on 2021-08-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praxismethoden', '0008_aufgaben'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='files',
            new_name='file',
        ),
    ]
