# Generated by Django 3.1.5 on 2021-09-09 09:33

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praxismethoden', '0009_auto_20210901_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw/', verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='method',
            field=models.ManyToManyField(blank=True, related_name='method_files', to='praxismethoden.Method'),
        ),
    ]
