# Generated by Django 3.1.5 on 2021-12-07 15:34

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praxismethoden', '0014_auto_20210914_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('overview', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='method',
        ),
        migrations.AddField(
            model_name='method',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='method_files', to='praxismethoden.File'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_kind', models.PositiveSmallIntegerField(choices=[(1, 'Meilenstein'), (2, 'Prüfungsleistung')], default=1, verbose_name='Art des Elements')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=510)),
                ('desc', ckeditor.fields.RichTextField(blank=True, help_text='Der hier eingegebene Text beschreibt die kurz das wichtigste zum Meilenstein.', null=True, verbose_name='Zusammenfassung')),
                ('tipp', ckeditor.fields.RichTextField(blank=True, help_text='Hier noch ein Text, welcher als Tipp zur Methode angezeigt wird.', null=True, verbose_name='Tipp')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='praxismethoden.course')),
                ('files', models.ManyToManyField(blank=True, related_name='module_files', to='praxismethoden.File')),
            ],
        ),
    ]
