# Generated by Django 3.1.5 on 2021-12-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praxismethoden', '0015_auto_20211207_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='summary',
            field=models.TextField(max_length=510),
        ),
    ]
