# Generated by Django 3.1.5 on 2021-12-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praxismethoden', '0016_auto_20211207_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aufgaben',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
