# Generated by Django 3.1.5 on 2021-12-07 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praxismethoden', '0017_auto_20211207_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='course_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
